run:
  timeout: 3m
  tests: true
  skip-dirs:
    - vendor

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - gosimple
    - unused
    - errcheck
    - typecheck
    - gocritic
    - revive
    - misspell
    - gosec
  disable:
    - depguard

linters-settings:
  revive:
    severity: warning
    rules:
      - name: exported
        arguments: ["disable"]
  misspell:
    locale: US
  gosec:
    excludes:
      - G306 # Allow file perms set explicitly in controlled scaffolding

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
